### ISSUE TITLE
@asyncConnect not working when using component wrapper in <Router

### ISSUE THREAD

**Issue by LennardWesterveld** [makeomatic/redux-connect#102]
Hi,

What i have is in my router `<Route path="info_post" component={Post} />` everything works fine. But i want to pass some props to the Post component because i need it for the rest call to the api. So i found on internet solution to do it this way: `<Route path={route.path} component={() => <Post id='1'/>} />` but when i do this my @asyncConnect doen't work anymore. Does any one know how to fix this?

```
@asyncConnect([{
  promise: ({store: {dispatch}}) => {
    return dispatch(getPost(1));
  },
}])
@connect(
  state => ({post: state.post})
)
```

**Comment by AVVS** [comment]
Wont work like this. You need to get data like this from ownProps of the router, there is no need to create wrapper functions. Please forget that pattern you’ve just used - it’s literally one of the worst practices
There are a few other issues that are open, specifically “blocking” ones that you should read through on why this can’t be done like this

As to how it should be done - use second and third arguments, which are respectively ownProps and Helpers. There is an open issue with docs for that

**Comment by LennardWesterveld** [comment]
Thanks for quick answer, yea I was thinking the same that this wasn't the right way. But can you give a example of ownProps solution?

**Comment by AVVS** [comment]
check https://github.com/makeomatic/redux-connect/issues/95

**Comment by AVVS** [comment]
and react-router documentation on what props are passed to the component thats in the route

**Comment by LennardWesterveld** [comment]
AVVS i see a interesting thing what maybe solve the <Route props problem see the new release of react-router: https://github.com/ReactTraining/react-router/blob/v4/README.md#why-the-huge-change
