### ISSUE TITLE
This library blocks a component render even if props have already been fetched

### ISSUE THREAD

**Issue by davidfurlong** [makeomatic/redux-connect#110]
This is kind of a performance tragedy, so I hope I've been doing something wrong.

Scenario: 

We have PageA and PageB, both `@asyncConnect`ed. they are as such:
```js
<Route path="/a" component={PageA}>
<Route path="/b" component={PageB}>
```
Now navigate between them on the client. Each navigation will block render until promises complete. However we only want this behaviour on first fetch (on server)

**Comment by AVVS** [comment]
you have to implement caching strategy to avoid that or not return the promise based on the `__CLIENT__` / `__SERVER__` checks, that issue has been raised earlier

**Comment by davidfurlong** [comment]
@AVVS  so its up to the user to do these checks in the promise functions?

**Comment by AVVS** [comment]
yes, because there is no silver bullet to all cases, hence it was left for the user to decide whether its caching or new request on each transition

**Comment by davidfurlong** [comment]
ah. I guess I was using it wrong. `redial` handles this by default
