### ISSUE TITLE
Server-side redirect in asyncConnect with react-router?

### ISSUE THREAD

**Issue by bertho-zero** [makeomatic/redux-connect#114]
How to do a redirection on server-side with react-router?

I have seen the issue #70 but I can not manage to do a server side redirection, I tried by dispatching a replace action of react-router-redux but nothing happens.

```js
import { asyncConnect } from 'redux-connect';
import { replace } from 'react-router-redux';

@asyncConnect( [ {
  promise: ( { store: { dispatch, getState }, router, ...props } ) => {
    const state = getState();

    if ( state.settings.isNew ) {
      return dispatch( replace( '/' ) );
    }
  }
} ] )
```

Thanks for your help.

edit: Yet in the `routing.locationBeforeTransitions` key of my store the location has changed well.

**Comment by AVVS** [comment]
do 

```js
if (__SERVER__) {
   // special logic for redirect
} else {
  // client logic
}
```

Problem with what you are suggesting is that you can't change URL of the browser from the server except for sending response with code 301/302 and new URL, so with normal redirects from router you can get redirect props and react to that, and, in this case you'd have to handle resulting state location vs current requested route and handle it somehow

**Comment by bertho-zero** [comment]
Finally I did this: https://github.com/bertho-zero/react-redux-universal-hot-example/commit/fd92d694574c161dc537282e0f3abbb54cb63446

**Comment by AVVS** [comment]
Glad you did! Do you want to add this as an example to this repo? I think others would appreciate it

**Comment by bertho-zero** [comment]
Oh yes of course !

**Comment by bertho-zero** [comment]
I opted for the following solution for the server:
```js
import verror from 'verror';

const redirect = to => {
  throw new VError({ name: 'RedirectError', info: { to } });
};

loadOnServer({ ...renderProps, store, helpers: { redirect } }).then(() => {
  /* ... */
  res.send(...);
}).catch(mountError => {
  if (mountError.name === 'RedirectError') {
    return res.redirect(VError.info(mountError).to);
  }
  /* ... */
});
```
