### ISSUE TITLE
Add example without decorators

### ISSUE THREAD

**Issue by Keats** [makeomatic/redux-connect#12]
Not everyone uses them

As an example here's how we use redux-async-connect (0.1) in our app:

```ts
class DashboardRoute extends React.Component<IDashboardRouteProps, {}> {
  static reduxAsyncConnect(params, store) {
    return Promise.all([store.dispatch(getDashboardData())]);
  }
}
```

What would be the equivalent in `redux-connect`? `getDashboardData` is a redux action here so we need the dispatch as well

**Comment by AVVS** [comment]
Decorator is a function that creates a wrapper component. So like with any other thing what you would do is asyncConnect(connect(component))

That is pseudocode, but I hope you get the example. There might be no connect part, etc.

Just understand that decorator is a syntactic sugar for creating a wrapped smth, ie class or fn

decorator(Mixed) returns WrappedMixed

**Comment by Keats** [comment]
I'm aware of that but was the feature of just using a static method removed since the version we're using?

**Comment by AVVS** [comment]
Its not a static method anymore, but a static property with an array in it
Code is here: https://github.com/makeomatic/redux-connect/blob/master/modules/containers/decorator.js

This is a wrapper:
https://github.com/makeomatic/redux-connect/blob/master/modules/containers/decorator.js#L10-L38

And then it adds a redux-connect wrapper, which maps all asyncItems with 'key' to components props:
https://github.com/makeomatic/redux-connect/blob/master/modules/containers/decorator.js#L44-L55
