### ISSUE TITLE
Wait for Nested Promises to resolve

### ISSUE THREAD

**Issue by kastsiushkin** [makeomatic/redux-connect#127]
I have a new requirement in the app and wondering if someone has any suggestions on how we can use `redux-connect` for it. I already use it in the app, sometimes waiting for multiple promises to resolve, but they are all independent. Now I have a nested API call that uses data returned by another call. Both calls need to resolve server side for SEO purposes.

1. Make first API call
2. Use data from first call to make second API call
3. Save data from both calls under different keys to reduxAsyncConnect

**Comment by AVVS** [comment]
nested components are waiting for the top upper layer promises to resolve, so just pick the data from your store - it will be available

**Comment by kastsiushkin** [comment]
It is happening at the top level component. The solution was to simply chain promises.
