### ISSUE TITLE
react-redux 6.0.0 support

### ISSUE THREAD

**Issue by internetErik** [makeomatic/redux-connect#133]
Currently this can't be used with react-redux v6 because they have switched over to the new context API. Currently it breaks when trying to get store from `this.context` in `component/AsyncConnect.js` `isLoaded` function.

For now the solution is to not update to react-router v6, but it would be nice 

May need a higher order component to get the store into there? Anyone have thoughts on how to approach this?

More information: https://blog.isquaredsoftware.com/2018/11/react-redux-history-implementation/#v6-0

**Comment by ioanlucut** [comment]
+1

**Comment by ioanlucut** [comment]
Hi! Is there any plan to support this upgrade? Thank you.

**Comment by AVVS** [comment]
there are plans to implement the changes, but we dont have a timeline for that yet. You are very welcome to take a stab at it and create a PR - will help to review it, and would happily mention you in the readme :)

**Comment by ioanlucut** [comment]
Hi @AVVS. I prepared the https://github.com/makeomatic/redux-connect/pull/135 PR
Please have a look. Thank you!

**Comment by ioanlucut** [comment]
Hello @AVVS! Sorry for stressing out. Do you have any time soon to look into this PR?
Or maybe can I do some kind of prerelease of this version until then?
Thanks a lot!

**Comment by ioanlucut** [comment]
Hello @AVVS :) Any chance we can get this PR merged and released?
Thanks a lot!

**Comment by AVVS** [comment]
Done :)

**Comment by ioanlucut** [comment]
@AVVS Thanks a ton!
