### ISSUE TITLE
Higher order components?

### ISSUE THREAD

**Issue by jtmarmon** [makeomatic/redux-connect#18]
I have a higher order component which handles protecting authenticated pages. It looks something like this:

```jsx
export default function requireAuthentication(Component) {
  componentWillMount() {
    // check if user is logged in. redirect to login page if not
  }

 render () {
   const userIsLoggedIn = // something
   return (
     <div>
      {userIsLoggedIn ? <Component {...this.props} /> : null}
    </div>
   )
 }
}
```

Then, in `routes.js` I have:

```jsx
return (
   ...
  <Route component={requireAuthentication(MyComponent)} path="/foo" />
  ...
)
```

When I use this `requireAuthentication` function, my asyncConnect promise is never called. When I remove the `requireAuthentication`, it is called. Is there a way I can get this to work?

**Comment by AVVS** [comment]
Use onEnter hook to check for authenticated user, async props can only be loaded for components that are returned from react-router during route matching

**Comment by jtmarmon** [comment]
Ah got it, thank you!
