### ISSUE TITLE
new react-router applyRouterMiddleware method

### ISSUE THREAD

**Issue by fabiozaffani** [makeomatic/redux-connect#2]
Hi,

Just wondering, how the code would be changed with the new applyRouterMiddleware method from react-router.

Currently in the example we have

`<Router render={(props) => <ReduxAsyncConnect {...props}/>} history={browserHistory}>`

Thinking we should have something like

`function useReduxConnect() {
  return {
    renderRouterContext: (child, props) => (
      <ReduxAsyncConnect {...props} />
    )
  };
}`

and then 

`<Router render={applyRouterMiddleware(useReduxConnect()} />} history={browserHistory}>`

But not really sure.

**Comment by AVVS** [comment]
Looks right to me
Reference on applyRouterMiddleware: https://github.com/reactjs/react-router/pull/3327

**Comment by AVVS** [comment]
Except we need to render `{child}`, otherwise all the content will disappear

**Comment by AVVS** [comment]
```js
function useReduxConnect() { 
  return { 
    renderRouterContext: (child, props) => {
      return (<ReduxAsyncConnect {...props} >{child}</ReduxAsyncConnect>);
    },
  }
}
```

**Comment by AVVS** [comment]
Actually the render method in ReduxAsyncConnect is the following:

```
  static defaultProps = {
    render(props) {
      return <RouterContext {...props} />;
    },
  };
```

At least by default. Therefore we need to swap it to support middleware. Can you describe use-case in more details? Why would you want to change the defaults that are here

**Comment by strawbrary** [comment]
If I understand correctly, the use case is to be able to use other `react-router` middleware. Something like:

```javascript
import useScroll from 'react-router-scroll'; // https://github.com/taion/react-router-scroll

const useReduxConnect = () => ({renderRouterContext: (child, props) => <ReduxAsyncConnect {...props}>{child}</ReduxAsyncConnect>});

<Router render={applyRouterMiddleware(useScroll(), useReduxConnect())} history={browserHistory} />
```

**Comment by AVVS** [comment]
I'll add tests & example, you can track progress here:

https://github.com/makeomatic/redux-connect/tree/feat/applyRouterMiddleware

**Comment by mmahalwy** [comment]
@strawbrary that could work. Here is my implementation: https://github.com/taion/react-router-scroll/issues/3

**Comment by AVVS** [comment]
Copying here for lazy people:

@mmahalwy this looks pretty good without any need to handle `{child}`. I will try to get some code in to get this use-case working as well, but if not - this solution does work

```
const component = (
  <Router
    render={(props) => (
      <ReduxAsyncConnect
        {...props}
        helpers={{client}}
        filter={item => !item.deferred}
        render={applyRouterMiddleware(useScroll())}
      />
    )}
    history={history}
    routes={getRoutes(store)}
  />
);
```

**Comment by fabiozaffani** [comment]
Hi @AVVS, sorry for the delay in answering here, mothers day and everything ;)

The use case is precisely what @strawbrary said, and for exactly same reason, since i'm currently with useScroll() in the applyMiddleware i'm currently using a custom solution very similar to what @strawbrary used. But i noticed that it also works with only <ReduxAsyncConnect {...props} /> without the {child} inside it (maybe because of the useScroll() being called after?)
