### ISSUE TITLE
Some confusion about store state.

### ISSUE THREAD

**Issue by thebearingedge** [makeomatic/redux-connect#23]
Hello, thanks for addressing this problem with routing and data fetching!

However, I am confused about managing state after it is loaded. Do I understand correctly that if I want to manage/update state in my store of a `userProfile` I need to capture it from a `LOAD_SUCCESS` action? I ask because the loading actions don't seem to be public exports.

```js
const userProfile = (state = {}, { type, payload }) => {

  if (type !== LOAD_SUCCESS && type !== PROFILE_UPDATE) return state

  if (type === LOAD_SUCCESS && payload.key === 'userProfile') return payload.data

  return { state, ...payload } 
}
```
Does that look right?

**Comment by AVVS** [comment]
No, just use decorator and dispatch actions as you normally do to load your data and make sure that your dispatched action returns a promise - then redux connect will delay rendering until data is fetched and your state is populated, try following examples and check testa for more insight

**Comment by thebearingedge** [comment]
Ok, thank you.
