### ISSUE TITLE
Getting a warning on 2.4.0

### ISSUE THREAD

**Issue by NSLS** [makeomatic/redux-connect#26]
After migrating to this fork from the original redux-async-connect package, I have encountered a problem with getting a warning with the text of "warning.js:44Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component."
Additional screenshot is provided.
![screenshot 2016-05-31 05 03 50](https://cloud.githubusercontent.com/assets/8458382/15661081/250b01dc-26ed-11e6-9070-ec0bb3df7a74.png)

Downgrading to 2.3.0 removes the problem.
Hope it helps!

**Comment by AVVS** [comment]
Please send the code. It seems like during route transition or smth similar  redux async connect provider is unmounted, but it must never happen

**Comment by AVVS** [comment]
This is the only place where it can happen, so unless the topmost component is unmounted - the error must not be there

https://github.com/makeomatic/redux-connect/blob/master/modules/components/AsyncConnect.js#L69

**Comment by AVVS** [comment]
@NSLS can you provide more code from your app? Router and render implementation is what I'm after

**Comment by NSLS** [comment]
I will as soon as I will return to my computer.
Just hold on for a while.

**Comment by NSLS** [comment]
So, basically my project was built using this boilerplate - https://github.com/erikras/react-redux-universal-hot-example. You can clone it and try to change redux-async-connect to redux-connect and see if the error pops up on your machine

**Comment by NSLS** [comment]
I have also noticed, that disabling redux devtools in my config solves the problem.

**Comment by AVVS** [comment]
Thats a problem with a kit, use external dev tools - they are better and you wont really see that issue. Also wont happen in production either. So I'd rather not do anything thats not needed

**Comment by NSLS** [comment]
Yes, turns out that I better off removing devtools. Thanks for help, issue is solved!
