### ISSUE TITLE
why add the data to the redux-connect store?

### ISSUE THREAD

**Issue by rkoberg** [makeomatic/redux-connect#28]
In https://github.com/makeomatic/redux-connect/blob/master/modules/store.js
```
  [LOAD_SUCCESS]: (state, { payload: { key, data } }) => ({
    ...state,
    loadState: {
      ...state.loadState,
      [key]: {
        loading: false,
        loaded: true,
        error: null,
      },
    },
    [key]: data,
  }),
```
Why add the requested data (```[key]: data,```) to the reduxAsyncConnect store state? Shouldn't this go to an action's targeted reducer? Just trying this out and I am using one of my own actions->reducers to set my store's state, but this data is also duplicated in the reduxAsyncConnect store's state. Is the intention to just keep everything in reduxAsyncConnect store's state and we should not be using our reducers for redux-connect 'stuff'?

**Comment by AVVS** [comment]
This part is controversial, but you ultimately control it yourself - if key is specified, then its saved into redux connect namespace, if not - its still fetched, but not saved there. 

Reasons for that, well, I cant really think of any, except for some specific business logic in yours or some1 elses app - its a feature, it doesnt really it memory (we save a pointer or a strings/number to smth that would end up somewhere else anyway).

Hope that answered your question

There is also a small bug (more like a branch of code that needs more work) that prevents filtered loads from server to trigger client data fetching, but thats likely not going yo affect you

**Comment by rkoberg** [comment]
Thanks, just leaving out the key works for me.
