### ISSUE TITLE
Not firing on my component

### ISSUE THREAD

**Issue by ciokan** [makeomatic/redux-connect#29]
I don't know if this is a bug or not. The `asyncConnect` decorator works on some components but it doesn't on other.

I have this component that is supposed to fetch some remote categories and construct a dropdown out of them. The component is placed inside a form which form is placed inside a container so this makes me think that maybe `asyncConnect` works only on components directly related to the routes maybe and not to nested components.

```
@asyncConnect([{
	promise: ({store: {dispatch, getState}}) => {
		const promises = [];
		console.log('asdasdasd');
		return Promise.all(promises);
	}
}])
export default class CategoriesDropdown extends Component {
        render() {
		const _this = this;

		return (
			<div>test</div>
		);
	}
}
```

I have placed a `console.log` inside there to see if the decorator is called whatsoever without any results. Any ideas why isn't the decorator firing?

**Comment by AVVS** [comment]
It only fires on the components returned from the router matcher. Anything nested wont be seen at pre-render time and, therefore, wont be triggered

**Comment by ciokan** [comment]
As I thought. Thanks @AVVS.
