### ISSUE TITLE
Getting empty result when rendered on server

### ISSUE THREAD

**Issue by sungwoncho** [makeomatic/redux-connect#32]
I am trying to use redux-connect for server side rendering. I have the following code for it (similar to [this](https://github.com/erikras/react-redux-universal-hot-example/blob/3e8453dba635c5792dc2ab61406bbe9545328b25/src/server.js#L92-L105) example):

```js
...
import { ReduxAsyncConnect, loadOnServer } from 'redux-connect';
...
      loadOnServer({ ...renderProps, store }).then(() => {
        const component = (
          <Provider store={store} key="provider" >
            <ReduxAsyncConnect {...renderProps} />
          </Provider>
        );

        res.status(200);

        global.navigator = {userAgent: req.headers['user-agent']};

        res.send('<!doctype html>\n' +
          renderToString(<Html assets={webpackIsomorphicTools.assets()} component={component} store={store} />
        ));
      });
...
```

But `component` is empty when I call `renderToString` with it.

The same code works when I use [redux-async-connect](https://github.com/Rezonans/redux-async-connect) v1.0.0-rc2. But in the latest 1.0.0-rc4, the same issue happens.

What am I missing?

**Comment by AVVS** [comment]
Its a different repo. Please look at differences first and at examples/tests provides

If you still have questions I'd be glad to help

**Comment by sungwoncho** [comment]
@AVVS I am using redux-connect 2.4.0, and also tried 2.3.0. Thought it was the repo for redux-connect. Am I mistaken?

**Comment by AVVS** [comment]
> The same code works when I use redux-async-connect v1.0.0-rc2. But in the latest 1.0.0-rc4, the same issue happens.

Syntax for this fork is a bit different, thats what I meant

**Comment by AVVS** [comment]
Make sure that you use decorator correctly:

```
@asyncConnect([{
  // optional
  key: 'lunch',
  // gets an object and must be destructed to access props! and it must return a promise, otherwise SSR wont wait for the async props
  promise: ({ params, helpers }) => Promise.resolve({ id: 1, name: 'Borsch' })
}])
```

**Comment by sungwoncho** [comment]
I got it to work now. Not sure what changed. Thanks for your help. Closing this.
