### ISSUE TITLE
Sample without Decorators

### ISSUE THREAD

**Issue by vpanjganj** [makeomatic/redux-connect#38]
Is it possible to update the doc by adding samples that don't use Decorator pattern?

**Comment by AVVS** [comment]
I would call it "complicated". Decorator does the following:

```js
Component.reduxAsyncConnect = wrapWithDispatch(asyncItems);
```

Where `wrapWithDispatch` is

```js
import { connect } from 'react-redux';
import { isPromise } from '../helpers/utils';
import { load, loadFail, loadSuccess } from '../store';

/**
 * Wraps react components with data loaders
 * @param  {Array} asyncItems
 * @return {WrappedComponent}
 */
function wrapWithDispatch(asyncItems) {
  return asyncItems.map(item => {
    const key = item.key;
    if (!key) {
      return item;
    }

    return {
      ...item,
      promise: options => {
        const { store: { dispatch } } = options;
        const next = item.promise(options);

        if (isPromise(next)) {
          dispatch(load(key));
          // add action dispatchers
          next.then(
            data => dispatch(loadSuccess(key, data)),
            err => dispatch(loadFail(key, err))
          );
        } else if (next) {
          dispatch(loadSuccess(key, next));
        }

        return next;
      },
    };
  });
}
```

**Comment by AVVS** [comment]
Furthermore, it connects state to the component like this:

```js
const finalMapStateToProps = (state, ownProps) => {
      const asyncStateToProps = asyncItems.reduce((result, { key }) => {
        if (!key) {
          return result;
        }

        return {
          ...result,
          [key]: state.reduxAsyncConnect[key],
        };
      }, {});

      if (typeof mapStateToProps !== 'function') {
        return asyncStateToProps;
      }

      return {
        ...mapStateToProps(state, ownProps),
        ...asyncStateToProps,
      };
    };

    return connect(finalMapStateToProps, mapDispatchToProps, mergeProps, options)(Component);
```

**Comment by vpanjganj** [comment]
It's mostly because I want to avoid decorator pattern. My containers simply export:
```
export default connect(mapStateToProps)(Home);
```

**Comment by AVVS** [comment]
well, then you should simply get into the concept of decorator, `connect` in your case is a decorator, everything that you should do is just:

`export default asyncConnect(asyncProps, mapStateToProps)(Home)`

**Comment by AVVS** [comment]
this is exactly the same as

```js
@asyncConnect(asyncProps, mapStateToProps)
class Home extends Component {
```

**Comment by vpanjganj** [comment]
Ah cool!

**Comment by AVVS** [comment]
@vpanjganj I guess this is resolved

**Comment by vpanjganj** [comment]
Yes thanks a lot. To be fair the only reason I wanted to avoid decorators was [this](http://babeljs.io/docs/plugins/transform-decorators/).

**Comment by casertap** [comment]
Awesome work, thank you very much to maintain and upgrade this project!
Sorry I still did not understand how to do it without decorators.
Going from the ```@connect``` to non decorator pattern was very easy.
Why do you say doing it for redux-connect is complicated ? Can you please tell me what it will look like using this example source code ?
https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/containers/Widgets/Widgets.js

**Comment by casertap** [comment]
When I look at this package, I can see that it provides an easy way to use the decorator or not.
https://github.com/markdalgleish/redial

**Comment by casertap** [comment]
Hi @AVVS I have trouble making this work.
How to you let say I have this:
```
function mapStateToProps(state) {
  return {
    directory: state.directory,
  };
}
function mapDispatchToProps(dispatch) {
  return { dispatch };
}
export default connect(mapStateToProps, mapDispatchToProps)(Search);
```
Now how do I add a asyncConnect ontop of this without using the decorator pattern?
Thanks

**Comment by nobuttsseb** [comment]
@vpanjganj gaearon explains that it is technically better to not use the decorator pattern. https://github.com/happypoulp/redux-tutorial/issues/87
