### ISSUE TITLE
Exceptions are being absorbed

### ISSUE THREAD

**Issue by ericmuyser** [makeomatic/redux-connect#41]
Just a heads up, exceptions seem to be silent for anything inside the `loadOnServer` callback. 

### Example

![image](https://cloud.githubusercontent.com/assets/156768/16363745/0b266fbc-3b89-11e6-9c9d-095c8b22db8b.png)

`view` here is suppose to be a component, but I rendered it as a string beforehand

I put a try/catch inside the callback, so I could find out this was happening:

```
{ [Invariant Violation: renderToString(): You must pass a valid ReactElement.] name: 'Invariant Violation', framesToPop: 1 }
```

**Comment by AVVS** [comment]
Likely you are using native promises and they eat the error

**Comment by AVVS** [comment]
I assume that had been resolved?

**Comment by ericmuyser** [comment]
Yah that totally worked. Thanks @AVVS 
It's my bad, but might be worthwhile putting that .catch in the example code.
Cheers! :)

**Comment by AVVS** [comment]
@ericmuyser PRs are very welcome, even this small 👍
