### ISSUE TITLE
Using with a wrapper

### ISSUE THREAD

**Issue by sungwoncho** [makeomatic/redux-connect#46]
I would like to know if it is possible to use `redux-connect` with a wrapper.

To only render a component for logged in users, I created a higher order component:

```js
import React from 'react';
import { connect } from 'react-redux';

export default function authWrapper(options = {}) {

  return (WrappedComponent) => {
    const AuthComponent = ({ user }) => {
      if (options.guest) {
        return (
          user ? <div>You are already logged in!</div> : <WrappedComponent />
        );
      } else {
        return (
          user ? <WrappedComponent /> : <div>Please sign in</div>
        );
      }
    };

    return connect(
      (state) => ({
        user: state.auth.user
      })
    )(AuthComponent);
  };
}
```

I am using it like the following:

```js
const ensureLoggedIn = authWrapper();

export default () => (
  <Route path="/" component={App}>
    <Route path="/cakes" component={ensureLoggedIn(Cakes)} />
  </Route>
);
```

I decorated `Cakes` component with `@asyncConnect` using `redux-connect` to fetch some data. Now that `Cakes` is wrapped by another component, `redux-connect` ignores the promises bound to `Cakes`.

What can I do do keep using my higher order component and redux-connect together?

**Comment by AVVS** [comment]
Use onEnter hook in the router to fetch user instead of HOC, or put asyncConnect on HOC

**Comment by AVVS** [comment]
This would work and is generally fine

**Comment by sungwoncho** [comment]
> Use onEnter hook

This sounds sensible.

> put asyncConnect on HOC

I wouldn't do this because HOC can wrap any components, and all those components might have different `asyncConnect`.

If my approach is generally fine, I will close this. Thank you.
