### ISSUE TITLE
Project dead? Alternative?

### ISSUE THREAD

**Issue by mmahalwy** [makeomatic/redux-connect#47]

**Comment by AVVS** [comment]
How so?

**Comment by mmahalwy** [comment]
No commits for a month now :(

**Comment by AVVS** [comment]
I dont see any feature requests I can address for a wide audience to make this better.

**Comment by hanjukim** [comment]
@mmahalwy why don't you issue at https://github.com/Rezonans/redux-async-connect what's your point?

**Comment by AVVS** [comment]
Anyway, if there is smth you need - please raise an issue. There are also a few ones, which you can help with.

Closing for now

**Comment by mmahalwy** [comment]
Sounds good, thanks @AVVS
