### ISSUE TITLE
Async connect gets fired before componentWillUnmount

### ISSUE THREAD

**Issue by NSLS** [makeomatic/redux-connect#49]
Hello. 
I have a pretty simple set up, a simple component, which dispatches a reset function in componentWillUnmount and a link, which routes on another page, where asyncConnect loads some data asynchronously. However, I have noticed, that an action in the next pages' asyncConnect gets dispached before the reset in the componentWillUnmount. 

My question is - how can I dispatch some actions in the componentWillUnmount before asyncConnect's promise is fired?

**Comment by AVVS** [comment]
use react-router on leave handler instead, that should be good enough for your case

**Comment by NSLS** [comment]
@AVVS Will try it out! Thanks for the help
