### ISSUE TITLE
I had a weird bug.

### ISSUE THREAD

**Issue by hanjukim** [makeomatic/redux-connect#50]
Just for sharing my experience. Maybe a solution to remove race condition bug.

### Situation
The bug makes my app to stop getting END_GLOBAL_LOAD, so does changing route too.

### Investigation
1. I have found that END_GLOBAL_LOAD is not responding when I start new START_GLOBAL_LOAD before previous END_GLOBAL_LOAD being called.
1. After this situation occurs mapSeries > iterateOverResults function in helpers/utils won't be called too.
1. I have digged into _promise2.default, found that Promise is babel-runtime's own implementation.

### Solution
I have replaced babel-runtime's Promise to Bluebird, and bug disappeared too.

Add below codes to webpack entry.
```Javascript
const Bluebird = require('bluebird');
Bluebird.config({ warnings: false });
Bluebird.onPossiblyUnhandledRejection(e => {
  throw e;
});
require('babel-runtime/core-js/promise').default = Bluebird;
```

**Comment by AVVS** [comment]
likely you had an error in your code and it got swollen by "native" promise implementation. This module used bluebird earlier on, but then switched to whats offered by the user implementing code.

end global load would only not be called if your promise map chain was rejected

**Comment by hanjukim** [comment]
But, it didn't rejected really. I have debugged really carefully.
