### ISSUE TITLE
@asyncConnect - does not work when changing the route

### ISSUE THREAD

**Issue by arman-mukatov** [makeomatic/redux-connect#53]
Hi guys!

During startup of my application, "@asyncConnect" works and receives data from the api server, but when i change current route(changing to another page), there "@asyncConnect" not working, why?

update:

After server side rendering is happening with correct redux state tree(when switching to a different page), client side is again making the API call and re rendering of react component is happening. Any idea how to avoid this?

**Comment by anhdn** [comment]
Hi @arman-mukatov, 

I have issue like you when change to another page, asyncConnect does not call again on client side. Do you have any ideas?
