### ISSUE TITLE
How to perform 'Loading' and 'Failure' rendering?

### ISSUE THREAD

**Issue by raymondsze** [makeomatic/redux-connect#56]
I would like to render the Loading component during promise is resolving, also would like to render a Failure component when promise got rejected.
What is the best way I can do that?

**Comment by AVVS** [comment]
Not really use this. Its essentially is for blocking route changes until state is resolved. But if you still do:

For rendering loader you need not return the promise from the async connect decorator on the client and set loading state during action initialization - that way we wont block rendering

**Comment by raymondsze** [comment]
So do we suppose to use the asyncConnect in nested component?
What I want to do is, there is some action triggered by user to make the nested component get unmounted and replaced by another new component. Therefore the componentWillMount and componentDidMount would be triggered in the new component. 
In this case , if the fetching is failed or during fetching, the component would be rendered blank?

**Comment by AVVS** [comment]
@raymondsze read through this thread: https://github.com/makeomatic/redux-connect/issues/45
