### ISSUE TITLE
Where to initialise state using async connect

### ISSUE THREAD

**Issue by davidfurlong** [makeomatic/redux-connect#58]
I'm struggling to find a way to use react states which are synced up to the value of async connect calls. In react we shouldn't mutate this.props nor mutate state in render. I have a button that makes an async request and toggles between two states, and should be in either of these states initially based on an async connect call. 

In the callback of the button click async requests I use setState to change the state, but Its unclear to me where I can set the state initially before render and after the async connect request has been called. ComponentDidMount doesn't seem to do the job.

**Where can I perform a callback on async completion to set the react state, or set the react state after the async has completed and before the component render has been called**

Thanks!

**Comment by AVVS** [comment]
1. resolve state via asyncConnect. Invoke some actions that mutate actual state when these actions resolve. For instance, use redux-thunk-fsa + redux-promise middleware to allow for async actions. Async connect is merely here for you to know when this initial state resolution has completed. It's idiomatic to use same actions you would usually do
2. connect state to your component in a container, mapping `state.somenamespace.value` to needed prop
3. based on (2) select proper field

**Comment by AVVS** [comment]
> Where can I perform a callback on async completion to set the react state, or set the react state after the async has completed and before the component render has been called


@davidfurlong are you looking to change your state after async finished running on server-side or client-side?

**Comment by davidfurlong** [comment]
I managed to get this to work by using props directly (mapStateToProps in the decorator) and by avoiding using react states. Thanks for the help! I meant on the client
