### ISSUE TITLE
Clarify filter (item.deferred) logic

### ISSUE THREAD

**Issue by oyeanuj** [makeomatic/redux-connect#60]
Hi @AVVS!  I understand how to use redux-connect to block rendering of the component until data is loaded and if I don't care about blocking, I end up going with `componentDidMount` to load data.

What I am still unclear about, and this maybe a noob question - is how to defer some data and not others? In various other threads, I see you mention the `filter` property but I wasn't sure how that exactly worked. Like on the main page, I do have something like this on the client.js code
``` javascript
filter={item => !item.deferred}
```

Maybe this is just a documentation issue, but I'd love to understand how the filter code works and how can I get the some data to block and others to defer. Here is what my code looks like today:

```javascript
@asyncConnect(
  [{
    promise: ({ location, params, store: { dispatch, getState } }) => {
      if (!isPostLoaded(getState(), params.postSlug)) {
        return dispatch(loadContent(params.postSlug));
      }
    }
  }],
  selectorList,
  mapDispatchToProps
)
```

Thank you!

**Comment by AVVS** [comment]
Hi @oyeanuj, deferred logic is currently flawed. Refer to other open issues please

**Comment by AVVS** [comment]
#45 and #30
