### ISSUE TITLE
IndexRedirect bug?

### ISSUE THREAD

**Issue by sebmor** [makeomatic/redux-connect#63]
I seem to have some trouble with this setup:

    <Route name="Home" path="/" component={App}>
        <IndexRedirect to="articles" />
        <Route name="Articles" path="articles">
            <IndexRoute component={Articles} />
            <Route path=":article" components={ArticleItem} />
        </Route>
    </Route>

With a straight forward AsyncConnect on Articles

    function mapStateToProps(state) {
      return {
        articles: state.articles
      }
    }

    function mapStateToPropsAsync({store: {dispatch}}) {
      return dispatch(fetchArticles())
    }

    const asyncItems = [{
      promise: mapStateToPropsAsync
    }]

    export default asyncConnect(asyncItems)(connect(mapStateToProps)(Articles))

Everything runs smooth when I go to /articles
But when I go to root, I get this error (but everything still renders fine):

    TypeError: Cannot read property 'length' of undefined

citing at eachComponents (node_modules/redux-connect/lib/helpers/utils.js:72:21)
at filterAndFlattenComponents (node_modules/redux-connect/lib/helpers/utils.js:98:3)
    at loadAsyncConnect (node_modules/redux-connect/lib/helpers/utils.js:121:19)
    at loadOnServer (node_modules/redux-connect/lib/helpers/utils.js:169:10)
    at reactMiddleware.js:20:5
    at node_modules/react-router/lib/match.js:65:5
    at handleErrorOrRedirect (node_modules/react-router/lib/createTransitionManager.js:124:39)
    at finishEnterHooks (node_modules/react-router/lib/createTransitionManager.js:109:41)
    at next (node_modules/react-router/lib/AsyncUtils.js:46:16)
    at loopAsync node_modules/react-router/lib/AsyncUtils.js:56:3)

Is this my wrong-doing or is there a bug with IndexRedirect?

**Comment by AVVS** [comment]
Looks like a bug with indexRedirect, let me take a closer look at the source

**Comment by AVVS** [comment]
check release 2.4.1, should fix your issue

**Comment by sebmor** [comment]
Can confirm 2.4.1 fixed this. Thanks for the swift response, you are a great maintainer!

**Comment by AVVS** [comment]
Thanks
