### ISSUE TITLE
Serialize?

### ISSUE THREAD

**Issue by webdif** [makeomatic/redux-connect#64]
In the README.md, there is a snippet example which use `serialize(store.getState())`.
What is that? I am certainly missing something here, but it's undefined to me.

Before using `redux-connect` I was using `JSON.stringify` to serialize my state object into a string to be able to pass it to html. But now, `JSON.stringify` block my server when there is an async action going on.

Any help? 😔

**Comment by AVVS** [comment]
Js is single threaded, it will block anyway

Problem is that stringidy is susceptible to attacks and you should use specific modules for that

**Comment by webdif** [comment]
OK.

So, instead of fetching data and returning the whole thing to `@asyncConnect`, it may be better to fetch the API I need, treat the data, and return to my component only the result (which will be a "safe" object, as I am the one creating it)?

And I figure that, as this object will be smaller, the serializing will be faster…

**Comment by webdif** [comment]
Just test that, it works now 🎉

**Comment by AVVS** [comment]
Yes, you should only serialize your processed state
