### ISSUE TITLE
usage as a HOC

### ISSUE THREAD

**Issue by GGAlanSmithee** [makeomatic/redux-connect#68]
From what I can tell it is possible to use `asyncConnect` as a higher order component, instead of as a decorator, but this is not documented anywhere AFAICT.

The reason why you might prefer a HOC to a decorator is that decorators have been a bit unstable. For example, they just reached stage-2 in es7 (with breaking changes) and still does not have an official babel plugin.

An example of usage as a HOC would be:

```javascript
import {connect} from 'react-redux'
import {asyncConnect} from 'redux-connect'

const Comp = ({info}) => (
    <h1>{info.id} {info.name}</h1>
)

const connectedComp = connect(
    mapStateToProps,
    mapDispatchToProps
)(Comp)

const connectedAsyncComp = asyncConnect([{
    key: 'info',
    promise: ({ params, helpers }) => Promise.resolve({ id: 1, name: 'Borsch' })
}])(connectedComp)
```

AFAICT, it works just fine using this as an HOC, and in this case I think it should be documented. If this usecase is not supported, please let me know.

**Comment by bentatum** [comment]
I agree, though - they are essentially the same thing.

Here's how I've been using it lately:

```js

import { PageHeader } from 'components'
import { default as React } from 'react'
import { asyncConnect } from 'redux-connect'
import { default as compose } from 'recompose/compose'
import { CategoriesList } from 'user/inventory/customer'
import { default as setDisplayName } from 'recompose/setDisplayName'
import { LOAD_CUSTOMER_CATEGORIES, loadCustomerCategories } from 'redux/modules/inventory'

const enhance = compose(
  setDisplayName('CustomerInventoryCategoriesPage'),
  asyncConnect([{ key: LOAD_CUSTOMER_CATEGORIES, promise: loadCustomerCategories }])
)

export default enhance(() =>
  <div>
    <PageHeader
      heading='Inventory Categories'
      breadcrumbs={[
        { children: 'Inventory', to: '/inventory', activeClassName: null },
        { children: 'Categories', to: '/inventory/categories' }
      ]}
    />
    <CategoriesList />
  </div>
)

```

**Comment by rkoberg** [comment]
I only use it as an HOC -- no decorators.

**Comment by GGAlanSmithee** [comment]
@bentatum you are right that a decorator conceptually is the same as a HOC, but looking at the recent changes to ES7 decorators, it might introduce friction between the two.

In an [issue over at the babel repo](https://phabricator.babeljs.io/T2645), @isiahmeadows gives a good summary of the changes and how they affect current decorator implementations. For example:

> Class decorators no longer take the class itself, but a descriptor consisting of the class, its parent class (i.e. `extends Parent) if one exists, and a set of MemberDescriptors on the class.

This is a breaking change, and depending on how this library adjusts, it might or might not support the usecase of using `asyncConnect` as a HOC.

I just think it would be nice to clarify if this is supported, and if so it should be included in the docs IMO.

**Comment by bentatum** [comment]
@GGAlanSmithee interesting, thanks for the heads up! I think you have a solid point, then.

**Comment by isiahmeadows** [comment]
Thanks, for the mention, but I'd like to clarify that the decorator
proposal shouldn't change much beyond what is accepted vs returned (you
could easily create a generic wrapper for legacy decorators for properties
and classes). The main difference is just the interfaces for the input and
output (e.g. to get the parent class, it's `desc.parent`, not
`Object.getPrototypeOf(Base)`).

**Comment by GGAlanSmithee** [comment]
Thanks for stopping by and clarifying @isiahmeadows. Sounds like it will be relatively easy for redux-connect to support both use-cases (HOC and decorator) even in the future, should they choose to.

**Comment by isiahmeadows** [comment]
Welcome! :-)
