### ISSUE TITLE
Chain promises of ajax calls

### ISSUE THREAD

**Issue by anaibol** [makeomatic/redux-connect#69]
Is it possible to chain promises with a depency between them?
For example, I need to fetch a user by username to get his id to fetch his chats

Like:

```javascript
export default asyncConnect([{
  key: 'user',
  promise: ({ store: { dispatch, getState }, params: { username } }) => {
    return dispatch(getUserByUsername(username))
  }
}, {
  key: 'chat',
  promise: ({ store: { dispatch, getState },  user: { _id }}) => {
    return dispatch(getChat(_id))
  }
}]
```

**Comment by AVVS** [comment]
Chain inside first promise. I assume you use promise-middleware, so smth like the snippet below could work

dispatch(action).then(response => dispatch(nextAction(response.payload.smth)))

**Comment by anaibol** [comment]
Ok, cool! I will maybe use it that way the next time, I finished making it with only one http call.

Thanks!
