### ISSUE TITLE
Server-side redirect in asyncConnect?

### ISSUE THREAD

**Issue by webdif** [makeomatic/redux-connect#70]
I use redux-connect to request data from a wp rest api. I have URLs like this: `/blog/page/2`, when I fetch the posts and display the result.

Now an example: if the user is typing manually `/blog/page/6` when I have only 4 pages, I want to redirect on `/blog`. Client-side, it's easy, I can use `browserHistory.replace('/blog')` from React-router. But what about server-side?

Thanks in advance for the help 👍

**Comment by AVVS** [comment]
in both client & server side you should use dispatch actions & react-router connected to redux

**Comment by webdif** [comment]
That's what I tried first, but my @asyncConnect function does not seem to get the `dispatch` prop 😕 
Do you know where I can find some example for this kind of things?

**Comment by AVVS** [comment]
it get store, and store has getState and dispatch in it

**Comment by webdif** [comment]
Thank you so much 🎉  !

**Comment by anaibol** [comment]
@AVVS can we do this without connecting redux to react-router? Like with @withRouter
I am trying to redirect on not found on the promise result.
