### ISSUE TITLE
Resolves on promise rejection

### ISSUE THREAD

**Issue by mykz** [makeomatic/redux-connect#71]
I'm not sure if this is expected behaviour or not.

I'm trying to get asyncConnect to catch promise rejections. With the below implementation it still seems to pass and not be caught.

Any help would be much appreciated.

```js
@asyncConnect[{
    promise: () => {
        let promises = [];

        promises.push(Promise.reject());

        return Promise.all(promises);
    }
}]);
```

```js
loadOnServer({ ...renderProps, store })
.then(() => {
    // Container to render
    const container = (
        <Provider store={store}>
            <ReduxAsyncConnect {...renderProps} />
        </Provider>
    );

    // Document to render
    const HTML = renderToStaticMarkup(
        <Root component={container} store={store} />
    );

    // Respond
    return response.status(200)
        .send('<!doctype html>\n' + HTML);
})
.catch(error => {
    return response.status(500)
        .send('Something went really bad :\'(');
});
```

**Comment by AVVS** [comment]
promise rejections are always caught and appropriate action is dispatched. Please refer to codebase for more samples. Its your responsibility to inspect state and handle errors

**Comment by mykz** [comment]
@AVVS Really appreciate the fast response on my issues.

I'll take look at the samples again and apply some error handling that I can read from the state before rendering to the server.

Cheers!
