### ISSUE TITLE
Server side rendering checksum mismatch

### ISSUE THREAD

**Issue by creativ** [makeomatic/redux-connect#72]
`redux-connect` integration works well for me, but on client side when page is rendering, client markup provided to _react-dom_ on mount contains react-empty, instead of rendered components (when it's loaded, markup is ok, but checksum already mismatch and ssr not working as it suppose).

As result, server rendered markup checksum mismatch with client rendered markup and page re-renders (which cause flickering and bad UX).

Integration seems to be correct:
- container components wrapped with `@asyncConnect` decorator and promise logic
- react-router renderer uses custom middleware with _ReduxAsyncConnect_

@AVVS Could you suggest some solution? Thanks!

**Comment by AVVS** [comment]
It should contain the complete html with correct checksum. Make sure ssr rendering is enabled. Try checking tests and sample code

**Comment by efernandesng** [comment]
I have same behavior when use `injectIntl` from `react-intl` module.

```javascript
import { injectIntl } from 'react-intl'
import { asyncConnect } from 'redux-connect'

@asyncConnect(...)
class MyComponent extends React.Component {
...
}

export default injectIntl(MyComponent)
```

**Comment by creativ** [comment]
@efernandesng In my case, an issue was on our side and I've solved it tracing `redux-connect`'s behaviour. **AsyncConnect** component source gives a valuable [hint](https://github.com/makeomatic/redux-connect/blob/master/modules/components/AsyncConnect.js#L67).

When we're sending rendered page to client, we missed to put in initial state information for `redux-connect` that data was loaded:
```js
const store = configureStore({
  reduxAsyncConnect: {
    loaded: true,
  },
});
```

Also, if you have some problem with *react-intl* integration not related to `redux-connect`, you can take a look at [mern boilerplate](https://github.com/Hashnode/mern-starter/), they have good integration sample of *react-intl*.

If it wouldn't help, feel free to send me an email or text me here.

**Comment by efernandesng** [comment]
@creativ thanks for you help :)

I had a problem with checksum mismatch, but it's because I update to react@15 and I forgot make all changes in client router.

I founded the answer to the problem with `injectIntl` in #45.

> What's not supported is a component, which renders a child component and that child component is actually a container with `asyncConnect` attached and it was not visible anywhere before that render() call in react occurred. In that case there is no way to find that static property on the container beforehand.

To resolve the problem, I create a decorator for `injectIntl` and put it after the `@asyncConnect`.

```javascript
import { injectIntl as inject } from 'react-intl'

export const injectIntl = options => component => inject(component, options)
```

Unfortunately, this doesn't solve my inital problem. I want translate some router params, but for it I need access `intl` prop directly from context  in `@asyncConnect`.. But I don't known how :(

**Comment by rkoberg** [comment]
Perhaps take a look at how Este does it. I posted an example in an issue here:
https://github.com/este/este/issues/1123#issuecomment-245442248
