### ISSUE TITLE
first entry page miss render

### ISSUE THREAD

**Issue by mhbseal** [makeomatic/redux-connect#73]
client render,async connect data,A(page) -> B(page),B render 1 times,but B(page) -> B(page),B render 3 times. eg.
https://github.com/erikras/react-redux-universal-hot-example,  Widgets Page.

```
@asyncConnect([{
  //deferred: true,
  promise: ({store: {dispatch, getState}}) => {
    //if (!isLoaded(getState())) {
      return dispatch(loadWidgets());
    //}
  }
}])
```

i think that asyncConnect don't inject loading and loaded state in first entry page!

**Comment by hanjukim** [comment]
loading and loaded state are managed by RRUHE's own redux module, not in redux-connect.
