### ISSUE TITLE
Reselect?

### ISSUE THREAD

**Issue by jerryharrison** [makeomatic/redux-connect#74]
I'm working on several new applications and projects and am starting "yet another react boilerplate repo," for personal use only.

I'm not new to react and have freelance-build several web apps for clients using react. In the past though to "connect/select" specific state for components I used [reselect](https://github.com/reactjs/reselect) and since the react eco-system is still in the wild west and new things are popping up everyday I stumbled across your module.

This seems very similar to reselect, but frankly looks a bit easier to use in terms of selecting the state for components and async'ing data into a component. I'm curious your thoughts on reselect and honestly if this is a similar library to it as I didn't see it listed in the readme.

Any thoughts or comments would be appreciated. I looked in the issues for a similar question and didn't find one so I hope I'm not repeating anyone.

Thank you!

**Comment by AVVS** [comment]
Hi @jerryharrison, relesect is used for a whole different thing. In a nut shell it's used to compute a derived state on the client side, and making sure we don't recompute it unless absolutely needed. As in any type of sort or filtering on existing data or lengthy computations - it gives a memoize function and makes sure that body is not invoked if input args are the same

This one solves SSR problem

**Comment by jerryharrison** [comment]
Gotcha. I think I was misreading the docs. Also when digging I never saw the two being used together.

 Thanks for the clarification.
