### ISSUE TITLE
Document: about redux-state

### ISSUE THREAD

**Issue by toriumi0118** [makeomatic/redux-connect#76]
This [redux-state](https://github.com/makeomatic/redux-connect/blob/master/docs/API.MD#redux-state) doc says I could get five state in `reduxAsyncConnect` state (loaded, [key].loading, [key].loaded, [key].data, [key].error).

But when I use it with some key (ex: names 'akey'), I could get the following.
- state.akey.loaded (true or false)
- state.akey (object which I wanted to get)
- state.loadState.akey (including error, loaded, loading states)

The structure is different with docs said.

Is it the document is wrong? or my way to use this module??

**Comment by hanjukim** [comment]
Are you using Redux DevTools? Action name like`@redux-conn/XX` changes reduxAsyncConnet.loadState.akey
