### ISSUE TITLE
Synchronous data loading with multiple asyncConnected components.

### ISSUE THREAD

**Issue by thomasdrakebjss** [makeomatic/redux-connect#78]
Hi, I am working on a project in which we use multiple components with asyncConnect decorators under a parent component. We do this by adding each of these components to the react-router component under "components" and naming them.

`<Route component={Home}>`
`<IndexRoute components={{ componentA: ComponentA, componentB: ComponentB}}/>`
`</Route>`

And then inside the Home component we place each of the asyncConnected components using {this.props.componentA} etc.

Resolving multiple promises in each individual component is fine, however resolving the promises on the list of components is done synchronously. i.e all promises are resolved on ComponentA asynchronously first, then all promises are resolved on ComponentB asynchronously.

Is this a feature or a bug? If its a bug I'll open a pull request for a fix.

**Comment by AVVS** [comment]
Since they are on the same level they should resolve asynchronously, making this a bug

**Comment by thomasdrakebjss** [comment]
Ok @AVVS, I have opened a pull request for a potential fix.

**Comment by AVVS** [comment]
@thomasdrakebjss Thanks a lot for the contribution. Merged in v4.0.0
