### ISSUE TITLE
Using with react container components  ? 

### ISSUE THREAD

**Issue by sagar12861** [makeomatic/redux-connect#84]
I'm using react-redux connect for isolating view component and state management.
Can any one suggest me the best way to handle use that along with @asyncConnect ?

**Comment by AVVS** [comment]
use asyncConnect instead of connect whenever you need your container to have async state resolved on SSR, besides that nothing changes. Make sure your container is resolved after react-router's match

**Comment by sagar12861** [comment]
If I no need to use connect then what is the alternate for mapStateToProps and mapDispatchToProps ?

**Comment by AVVS** [comment]
https://github.com/makeomatic/redux-connect/blob/master/modules/containers/decorator.js#L41-L50

**Comment by sagar12861** [comment]
Ho I'm sorry I haven't found this doc before https://github.com/makeomatic/redux-connect/blob/master/docs/API.MD Now I'm reading it.

**Comment by altayaydemir** [comment]
@sagar12861 Here's a basic example that might be useful for you: https://github.com/LaborWorks/react-redux-training/blob/master/04-redux-todolist-typescript/src/app/containers/TodoList/index.tsx

**Comment by sagarrayudu** [comment]
Thanks @AVVS and @altayaydemir I'm able to understand and working now.
