### ISSUE TITLE
MIgrate to react router v3

### ISSUE THREAD

**Issue by Iuriy-Budnikov** [makeomatic/redux-connect#86]
redux-connect@2.4.1 requires a peer of react-router@~2.x.x but none was installed.

**Comment by Iuriy-Budnikov** [comment]
Hey guys.

Is this module still maintained?

**Comment by AVVS** [comment]
Yes it is

**Comment by AVVS** [comment]
Use redux-connect@4.x.x, it supports react-router 3.x.x

**Comment by AVVS** [comment]
in fact there are no changes, so you are just fine with 2.x.x, too

**Comment by Iuriy-Budnikov** [comment]
@AVVS ty
