### ISSUE TITLE
using @asyncConnect @and connect

### ISSUE THREAD

**Issue by alecperkey** [makeomatic/redux-connect#9]
Hi, 

I see now the @asyncConnect supports non-promises on the promise key of the 'asyncItems' objects.

When/why would one want to do this? 

Only reason I can think is to reduce code by having only one decorator (@asyncConnect) rather than two (@connect and @asyncConnect).

thanks

**Comment by AVVS** [comment]
Primarily this is to use cached results and reduce loading time, because on every route transition it will try to fetch all async props again. And its ultimately your decision when it should refetch it or use that data from store without triggering any actions

**Comment by AVVS** [comment]
As for connect you still should use it, because it does other things in terms of rerendering

**Comment by AVVS** [comment]
Closing this for now, since I dont see more questions right now

**Comment by AVVS** [comment]
@alecperkey I'm updating asyncConnect to allow one to use one of them instead of both when needed:

https://github.com/makeomatic/redux-connect/pull/14
