### ISSUE TITLE
API request header IP

### ISSUE THREAD

**Issue by bassbump** [makeomatic/redux-connect#93]
This may be intended, but I was wondering; I have a get request that I do with axios. When this happens on the client, it will send headers with the IP address of the user in it.

However, when I send it from the server through redux-connect, the axios request will send the IP address of the server, so http://localhost:3000 instead.

I was wondering is there a way, when axios is loaded async, to also return the headers with the IP address of the user, instead of the server?

**Comment by hanjukim** [comment]
I think you will have to pass your ip address (i.e. req.remoteAddress) to your loadOnServer function.

**Comment by dawidvdh** [comment]
@hanjukim how would you go about passing headers to the loadOnServer function?

**Comment by AVVS** [comment]
@dawidvdh through helpers / utilities
