### ISSUE TITLE
asyncConnect dependency

### ISSUE THREAD

**Issue by arasmussen** [makeomatic/redux-connect#96]
Is there any way to make the asyncConnect for one route depend on another finishing first? I have data where I can't load part 2 until part 1 is loaded.

I've read all the API, issues, and docs and don't see anything about this. Maybe do a `return dispatch(loadPartOne()).then(dispatch(loadPartTwo())` kinda thing?

**Comment by AVVS** [comment]
Make these routes nested and connect needed data from the state
