### ISSUE TITLE
React empty component on first load

### ISSUE THREAD

**Issue by nicolashemonic** [makeomatic/redux-connect#99]
Hi :)

I found an issue when i connect an asyncProp to a component which is the first route matched by react router on the first app loading.

Router wait correctly until the async task is complete but the default DOM displayed to the user:

`<div id="root"><p>Initializing...</p></div>`

Is replaced by a comment of react:

`<div id="root"><!-- react-empty: 1 --></div>`

I think it's because redux-connect return an empty (null) component until the async loading of the component is done.

I'm sure you understand it's a problem because an application can't show "nothing" to the user until she's ready.

There is a workaround to keep the default state in the DOM ? Or a workaround to define a component to display as a loading screen until the first loading of the application is done ?

Thank you very much per advance !

Nicolas

**Comment by dlakata** [comment]
Here's a workaround:

### index.html
```html
<html>
  <body>
    <div id="root"></div>
    <script src="bundle.js"></script>
  </body>
</html>
```

### bundle.js
```javascript
const initialize = (name) => new Promise((resolve) => {
  window.setTimeout(() => {
    resolve(name);
  }, 2000);
});

@asyncConnect([{
  key: 'name',
  promise: () => initialize('foo')
}])
class Index extends React.Component {
  render() {
    return (
      <div>
        <Link to="/test">Test</Link>
        <div>{this.props.name}</div>
      </div>
    )
  }
}

@asyncConnect([{
  key: 'name',
  promise: () => initialize('bar')
}])
class Test extends React.Component {
  render() {
    return (
      <div>
        <Link to="/">Index</Link>
        <div>{this.props.name}</div>
      </div>
    )
  }
}

@connect(
  state => ({
    loaded: state.reduxAsyncConnect.loaded
  })
)
class Initial extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      initialLoadComplete: false
    };
  }

  componentWillReceiveProps(nextProps) {
    this.setState({
      initialLoadComplete: this.state.initialLoadComplete || nextProps.loaded
    });
  }

  render() {
    return <div>
      {!this.state.initialLoadComplete ? <p>Initializing...</p> : null}
      {this.props.children}
    </div>
  }
}

const store = createStore(combineReducers({reduxAsyncConnect}));

render((
  <Provider store={store} key="provider">
    <Initial>
      <Router render={(props) => <ReduxAsyncConnect {...props}/>}
              history={browserHistory}>
        <Route path="/" component={Index}/>
        <Route path="/test" component={Test}/>
      </Router>
    </Initial>
  </Provider>
), document.getElementById('root'));
```

**Comment by nicolashemonic** [comment]
Hello @dlakata 

It works perfectly ! Thank you very much ;)

I think it should be added to the wiki, i will send a pull request...

Thanks !
